### ISSUE TITLE
Benchmarking can be done better

### ISSUE THREAD

**Issue by Bertg** [mrtyormaa/redisTest#1]
Ruby has a built in library called benchmark!

But even better is the [benchmark-ips](https://github.com/evanphx/benchmark-ips) gem. Exactly wha this test needs ;)

**Comment by mrtyormaa** [comment]
Thanks a lot for the useful tip. I will implement it. 

I am new to Ruby and hence in the process of exploring the full potential of Ruby. 

Thanks

P.S.: I will be looking forward for more comments like this in future. :)
